import type { Pin } from "./types";

// Tiny placeholder dataset so an empty map is never shown before Supabase is
// wired up. Replace with real submissions once the DB is live.
export const SEED_PINS: Pin[] = [
  {
    id: "seed-vashi-1",
    type: "lister",
    lat: 19.0772,
    lng: 73.0,
    node: "vashi",
    sector: "17",
    society: null,
    bhk: "2BHK",
    rent: 38000,
    furnishing: "semi-furnished",
    gated: true,
    parking: 1,
    deposit_months: 3,
    pet_ok: false,
    gender_pref: "any",
    diet_pref: "any",
    smoking_pref: "no",
    notes: null,
    created_at: new Date().toISOString(),
    expires_at: null,
    hidden: false,
  },
  {
    id: "seed-kharghar-1",
    type: "lister",
    lat: 19.0478,
    lng: 73.07,
    node: "kharghar",
    sector: "20",
    society: null,
    bhk: "1BHK",
    rent: 18000,
    furnishing: "unfurnished",
    gated: true,
    parking: 1,
    deposit_months: 2,
    pet_ok: true,
    gender_pref: "any",
    diet_pref: "any",
    smoking_pref: "any",
    notes: null,
    created_at: new Date().toISOString(),
    expires_at: null,
    hidden: false,
  },
  {
    id: "seed-nerul-1",
    type: "seeker",
    lat: 19.034,
    lng: 73.02,
    node: "nerul",
    sector: null,
    society: null,
    bhk: "2BHK",
    rent: 30000,
    furnishing: null,
    gated: null,
    parking: null,
    deposit_months: null,
    pet_ok: null,
    gender_pref: "any",
    diet_pref: "veg",
    smoking_pref: "no",
    notes: "Looking for a flatmate, move-in next month.",
    created_at: new Date().toISOString(),
    expires_at: null,
    hidden: false,
  },
  // The domain easter egg — the site itself is also up for rent.
  // Coordinates: ~Belapur CBD (HQ of CIDCO). Discoverable, not advertised.
  {
    id: "seed-domain",
    type: "lister",
    lat: 19.0235,
    lng: 73.0395,
    node: "belapur",
    sector: null,
    society: "navimumbai.rent (this domain)",
    bhk: "1BHK",
    rent: 0,
    furnishing: null,
    gated: null,
    parking: null,
    deposit_months: null,
    pet_ok: null,
    gender_pref: "any",
    diet_pref: "any",
    smoking_pref: "any",
    notes:
      "This pin is for the domain navimumbai.rent itself. BHK: 1 domain. Rent: negotiable. Contact the owner on the FAQ page.",
    created_at: new Date().toISOString(),
    expires_at: null,
    hidden: false,
  },
];
